export default [
    {
      id: '2Care',
      title1: '2Care',
      title2: 'Final project @LeWagon',
      subtitle: 'Keeping Families Informed',
      img1: require('./assets/images/projects/2Care/2Care.png'),
      img2: require('./assets/images/projects/2Care/2Care-details.png'),
      urlProj: 'https://app-2care-7e485396212c.herokuapp.com/',
      urlGitHub: 'https://github.com/AntQua/app-2care',
      description1: '2Care is the final project of my Web Development bootcamp at LeWagon, Lisbon, finished in 8th September 2023. It was a collaborative effort by a team of four dedicated student finalists.',
      description2: '<p>Want to have some fun? Check the <a href="https://www.youtube.com/watch?v=TtFWVkDVefA" target="_blank">project video presentation</a> (from minute 13) at Le Wagon Lisbon Demo Day, in the 8th of September 2023.</p>',
      description3: '2Care is a web application designed to bridge the communication gap between elderly care homes and the families of their residents. It specifically caters to elderly homes and families with loved ones residing in such facilities.',
      description4: 'The app offers a unique solution, enabling elderly care homes to monitor the well-being of their residents and share this vital information with registered family members via email notifications.',
      description5: "2Care was built using the Ruby on Rails framework and deployed on <strong>Heroku</strong>. The email functionality was implemented using <strong>SendGrid</strong>. The app's design was meticulously crafted with <strong>Figma</strong>."
    },
    {
        id: 'Botanika',
        title1: 'Botanika',
        title2: 'Individual project',
        subtitle: 'e-commerce web app',
        img1: require('./assets/images/projects/Botanika/Botanika.png'),
        img2: require('./assets/images/projects/Botanika/Botanika-details.png'),
        urlProj: 'https://cloud462022.azurewebsites.net/',
        urlGitHub: 'https://github.com/AntQua/Botanika',
        description1: 'Botanika is my final project of the Software Development Academy at Rumos, Lisbon, finished in May 2022.',
        description2: 'Botanika is a cloud software solution for gardenig enthusiasts which includes the online sale of flowers, plants and products for their cultivation.',
        description3: 'Environment and used Tools:',
        description4: 'The Admin / BackOffice Area:',
        description5: 'Azure Resources:'
      },
      {
        id: 'MyLibrary',
        title1: 'MyLibrary',
        title2: 'Individual project',
        subtitle: 'My Library Project',
        img1: require('./assets/images/projects/MyLibrary/MyLibrary.png'),
        img2: require('./assets/images/projects/MyLibrary/MyLibrary-details.png'),
        urlProj: 'https://antqua.github.io/MyLibrary/',
        urlGitHub: 'https://github.com/AntQua/MyLibrary',
        description1: 'MyLibrary is a single page who allows the user to input its favourit books and keeping track of its read status.',
        description2: 'Note that there is no back-end so the books are not stored in a database so they will vanish when the page is reloaded. The goal of this project was just for training.',
        description3: 'MyLibrary</a> was built using only <strong>HTML</strong>, <strong>CSS</strong> and <strong>JavaScript</strong> and deployed on <strong>GitHub Pages</strong>',
        description4: '',
        description5: ''
      },
      {
        id: 'Portfolio',
        title1: "Cera's Portfolio",
        title2: 'Group project',
        subtitle: 'Cera Kocher Portfolio',
        img1: require('./assets/images/projects/Portfolio/Portfolio.png'),
        img2: require('./assets/images/projects/Portfolio/Portfolio-details.png'),
        urlProj: 'https://antqua.github.io/brainnest-portfolio/',
        urlGitHub: 'https://github.com/AntQua/brainnest-portfolio',
        description1: "Cera's Portfolio</a> is a group project (team of 4) for the Brainnest Frontend Development Advanced Industry Training program, between February and May 2023.",
        description2: "Cera's Portfolio is a single page who displays the profile and work of the creative director, designer and photographer Cera Kosher, one of my colleagues in the program.",
        description3: 'This project was built using only <strong>HTML</strong>, <strong>CSS</strong> and <strong>JavaScript</strong> and deployed on <strong>GitHub Pages</strong>',
        description4: '',
        description5: ''
      },
      {
        id: 'SandSpot',
        title1: "SandSpot",
        title2: 'Group project @LeWagon ',
        subtitle: 'book your place in the sand',
        img1: require('./assets/images/projects/SandSpot/SandSpot.png'),
        img2: require('./assets/images/projects/SandSpot/SandSpot-details.png'),
        urlProj: 'https://whispering-meadow-11582-97e69ce26db6.herokuapp.com/',
        urlGitHub: 'https://github.com/AntQua/sandspot',
        description1: "SandSpot is a group project of my Web Development bootcamp at LeWagon, Lisbon, finished in 8th September 2023. It was a collaborative effort by a team of four dedicated students at the bootcamp.",
        description2: "SandSpot is a web application designed to find beaches all arround the world and book a place in the sand.",
        description3: 'The app offers 3 booking options for any beach available.',
        description4: "SandSpot was built using the <strong>Ruby on Rails</strong>  framework and deployed on <strong>Heroku</strong>. The app's design was crafted with <strong>Figma</strong>.",
        description5: ''
      },
      {
        id: 'Whatchlist',
        title1: "Whatchlist",
        title2: 'Solo project @LeWagon',
        subtitle: 'movies list by category',
        img1: require('./assets/images/projects/Whatchlist/Watchlist.png'),
        img2: require('./assets/images/projects/Whatchlist/Watchlist-details.png'),
        urlProj: 'https://antqua-movies-289be53429bf.herokuapp.com/',
        urlGitHub: 'https://github.com/AntQua/rails-watch-list',
        description1: "WhatchList is a individual project of my Web Development bootcamp at LeWagon, Lisbon, finished in 8th September 2023.",
        description2: "Watchlist is a web application designed to create movies categories and for each category create a personal movies list.",
        description3: "Watchlist was built using the <strong>Ruby on Rails</strong>  framework and deployed on <strong>Heroku</strong>. The app's images are stored on <strong>Cloudinary</strong>.",
        description4: '',
        description5: ''
      },
      
  ];
  